version: '3.1'

services:
  db:
    container_name: moonStore
    image: mongo:latest
    restart: always
    volumes:
      - ./.dbData:/data/db
    ports:
      - 27017:27017
  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      # need to understand this path
      - ./.sessionsData:/data
